### ISSUE TITLE
something wrong with http provider

### ISSUE THREAD

**Issue by azulay7** [Tgure/ngx-loggly-logger#1]
![untitled](https://cloud.githubusercontent.com/assets/19120/19679413/4e023b4c-9aaa-11e6-842e-99f09e286d24.png)

zone.js:357Error: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent - inline template:7:0 caused by: No provider for Http!(…)consoleError @ zone.js:357_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386
client?93b6:38 [WDS] Errors while compiling.

I think this solution is adjust to previous BETA version of angular2, cause is looking for HTTP_PROVIDERS.

**Comment by Tgure** [comment]
@azulay7 You are correct, the project I use it in has HTTP_PROVIDERS imported which is why it works for me.  I will be super busy for awhile but will try and get this updated to work without that as soon as I can.

**Comment by azulay7** [comment]
Thank you very much. Does the logger work fluelessly In your project?

**Comment by Tgure** [comment]
Yeah I have it running in two Angular 2.0.0 apps and it works just fine.  Both apps started in RC versions of Angular so have only been updated to 2.0.0 but do still have some deprecated RC stuff lingering.

**Comment by azulay7** [comment]
My apology,  I have a few questions: 
Can you config  the logger to log to a remote server? 
Does it work with appender?
Does it uses framework such as log4j?
Can you please describe each parmas:
// Init to set key and tag and sendConsoleErrors boolean  
this._logglyService.push({
    'logglyKey': 'Your Loggly Key goes here',
    'sendConsoleErrors' : true, // Optional set true to send uncaught console errors
    'tag' : 'loggly-logger'
});

**Comment by Tgure** [comment]
This is only made to work with an account with Loggly, https://www.loggly.com/.  The logglyKey is your key you get in your loggly account, sendConsoleErrors will log uncaught errors that typically go to console to loggly as well if set to true, and the tag is just whatever you want your logs tagged in Loggly.
