### ISSUE TITLE
Angular Universal document is not defined 

### ISSUE THREAD

**Issue by danduh** [Tgure/ngx-loggly-logger#11]
While trying to run with angular universal (SSR) getting the following error:
```
ReferenceError: document is not defined
  at new LogglyService
```
Related to 
```
this.LOGGLY_INPUT_PREFIX = 'http' + (('https:' === document.location.protocol ? 's' : '')) + '://';
```

Angular universal don't like 'document' object

**Comment by Tgure** [comment]
@danduh I have removed document, please try version 7.0.2
