### ISSUE TITLE
ngx-loggly-logger.js depends on 'ng2-cookies'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by eso32** [Tgure/ngx-loggly-logger#20]
Hey,

Is this a known issue? I'm getting this error on angular 10 and 11:
Warning: <project name>/node_modules/ngx-loggly-logger/__ivy_ngcc__/fesm2015/ngx-loggly-logger.js depends on 'ng2-cookies'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by Tgure** [comment]
That is just a warning, in your angular.json under allowedCommonJsDependencies you can add ng2-cookies as an allowed dependency and the warning will go away.
