### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by W0GER** [Tgure/ngx-loggly-logger#24]
Hello Tgure, 

Thank you for this OpenSource project, my team has been using ngx-loggly-logger for a couple of years, and it's worked great!

My team is interested in upgrading this package to be compatible with Angular 16. We've forked the repo to make changes. I wanted to reach out to you to see if you would prefer a Pull Request or if you'd rather add us as contributors to the project and the npm registration for ngx-loggly-logger ? 

Hope to hear back from you.

**Comment by Tgure** [comment]
Hey Roger,

Either way works for me but I sent you an invite from GitHub to be a collaborator.  I can add you to npm as well just need your username for npm.

Thanks

Aaron

**Comment by W0GER** [comment]
Aaron,

Thanks for the response. I'll have my team start working on the fork of the project, once we have something we'll PR it into your repo. I think that's probably the best approach. 

Thanks,
Roger
