### ISSUE TITLE
Update for Ivy

### ISSUE THREAD

**Issue by mikkimichaelis** [Tgure/ngx-loggly-logger#25]
I am encouraging the author to please update this great tool to support Ivy.

If the author is not able at this time to perform updates, I would be willing to attempt them myself.  Help from the author or community would be greatly appreciated.

Thank you

**Comment by Tgure** [comment]
I no longer use this library, can you tell me what you need updated?

**Comment by mikkimichaelis** [comment]
Hello and thank you for your fast response.  I found a fork of this repo which has been updated for the Angular Ivy view engine.  https://github.com/slaroc/ngx-loggly-logger.git
