### ISSUE TITLE
Does not work with AoT compiling

### ISSUE THREAD

**Issue by GenZodd** [Tgure/ngx-loggly-logger#4]
I am using webpack, via the angular2-webpack-starter. Once I add this module AoT compile no longer works. Here is the error I get.

Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in D:/project/node_modules/angular2-loggly-logger/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in D:/project/node_modules/angular2-loggly-logger/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in D:/project/node_modules/angular2-loggly-logger/node_modules/@angular/core/src/di/opaque_token.d.ts

**Comment by Tgure** [comment]
@GenZodd I grabbed a fresh angular2-webpack-starter and added the logger and was not able to reproduce the error, but did see other errors so corrected them.  I also went ahead and updated several dependencies as they were pretty out of date.  Try version 0.0.10 and let me know if you still have issues.

**Comment by GenZodd** [comment]
Thanks @Tgure! I cleaned up a few things as well and grabbed version 10 and AoT is now working.
