### ISSUE TITLE
Error: No provider for LogglyService!

### ISSUE THREAD

**Issue by doender** [Tgure/ngx-loggly-logger#6]
Using Angular 4 and ngx-loggly-logger 4, and following the new instructions, I get the following error:
```
AppComponent_Host.html:1 ERROR Error: No provider for LogglyService!
```

**Comment by Tgure** [comment]
@doender I will look into it when I get some time, for now in your app.module add this import and add LogglyService to your list of providers and that should resolve that error.

import { LogglyService } from 'ngx-loggly-logger/dist/src/loggly.service';

**Comment by doender** [comment]
I noticed I could fix it by calling the `forRoot()` function (`imports: [NgxLogglyModule.forRoot()]`)

**Comment by Tgure** [comment]
@doender Nice thanks for the info.
