### ISSUE TITLE
Blank page when viewing production build

### ISSUE THREAD

**Issue by onstottj** [Tgure/ngx-loggly-logger#7]
Hi,

When I run "ng build --prod" and deploy my site on a webserver, all I see is a blank page.  There aren't any JS errors, or failed network requests.

When I remove the ngx-loggly-logger library and comment out the parts of my code that use it, my site works fine.  I'm using the latest version of the library (a 4.x version), against Angular 4.

Any thoughts?  Thanks!
-Jon

**Comment by othenos** [comment]
I have the same issue. It can be worked around by using the --no-aot option on the build.

**Comment by Tgure** [comment]
@onstottj @mike-robinson I will try and recreate and find a fix for it, thanks for the work around for now Mike.

**Comment by Tgure** [comment]
@onstottj @mike-robinson If either of you get a chance try npm install ngx-loggly-logger@4.0.6 and let me know if that fixes the blank screen thing for you guys.

**Comment by othenos** [comment]
@Tgure Yep, that seems to do the trick. No issues observed when building and running production. Thanks for your efforts.

**Comment by Tgure** [comment]
Awesome thanks for the feedback
